// 
// Main website for TVRename is http://tvrename.com
// 
// Source code available at http://code.google.com/p/tvrename/
// 
// This code is released under GPLv3 http://www.gnu.org/licenses/gpl.html
// 

// 
// The initial version of this source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
// Save http://localhost:8080/sabnzbd/api?mode=queue&apikey=...&start=0&limit=9999&output=xml as sab.xml
// xsd.exe sab.xml
// xsd.exe sab.xsd /c /edb

using System;
using Alphaleonis.Win32.Filesystem;
using System.Xml.Serialization;
using System.IO;

namespace TVRename.SAB
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public class queue : object, System.ComponentModel.INotifyPropertyChanged
    {
        public static queue Deserialize(byte[] data)
        {
            MemoryStream ms = new MemoryStream(data);
            XmlSerializer serializer = new XmlSerializer(typeof (queue));
            try
            {
                queue r = (queue) serializer.Deserialize(ms);
                return r;
            }
            catch
            {
                return null;
            }
        }

        private string uniconfigField;

        private string cache_sizeField;

        private string active_langField;

        private string pausedField;

        private string sessionField;

        private string restart_reqField;

        private string power_optionsField;

        private string speedField;

        private string helpuriField;

        private string sizeField;

        private string uptimeField;

        private string refresh_rateField;

        private string my_homeField;

        private string limitField;

        private string have_quotaField;

        private string isverboseField;

        private string startField;

        private string finishField;

        private string versionField;

        private string new_rel_urlField;

        private string my_lcldataField;

        private string color_schemeField;

        private string diskspacetotal1Field;

        private string ntField;

        private string statusField;

        private string last_warningField;

        private string have_warningsField;

        private string cache_artField;

        private string sizeleftField;

        private string finishactionField;

        private string paused_allField;

        private string quotaField;

        private string newzbin_urlField;

        private string new_releaseField;

        private string pause_intField;

        private string mbleftField;

        private string diskspace1Field;

        private string scriptsField;

        private string darwinField;

        private string timeleftField;

        private string mbField;

        private string noofslotsField;

        private string etaField;

        private string diskspacetotal2Field;

        private string nzb_quotaField;

        private string loadavgField;

        private string cache_maxField;

        private string kbpersecField;

        private string speedlimitField;

        private string webdirField;

        private string queue_detailsField;

        private string left_quotaField;

        private string diskspace2Field;

        private queueSlotsSlot[] slotsField;

        private queueCategories[] categoriesField;

        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uniconfig
        {
            get { return uniconfigField; }
            set
            {
                uniconfigField = value;
                RaisePropertyChanged("uniconfig");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cache_size
        {
            get { return cache_sizeField; }
            set
            {
                cache_sizeField = value;
                RaisePropertyChanged("cache_size");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string active_lang
        {
            get { return active_langField; }
            set
            {
                active_langField = value;
                RaisePropertyChanged("active_lang");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paused
        {
            get { return pausedField; }
            set
            {
                pausedField = value;
                RaisePropertyChanged("paused");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string session
        {
            get { return sessionField; }
            set
            {
                sessionField = value;
                RaisePropertyChanged("session");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string restart_req
        {
            get { return restart_reqField; }
            set
            {
                restart_reqField = value;
                RaisePropertyChanged("restart_req");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string power_options
        {
            get { return power_optionsField; }
            set
            {
                power_optionsField = value;
                RaisePropertyChanged("power_options");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string speed
        {
            get { return speedField; }
            set
            {
                speedField = value;
                RaisePropertyChanged("speed");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string helpuri
        {
            get { return helpuriField; }
            set
            {
                helpuriField = value;
                RaisePropertyChanged("helpuri");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string size
        {
            get { return sizeField; }
            set
            {
                sizeField = value;
                RaisePropertyChanged("size");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uptime
        {
            get { return uptimeField; }
            set
            {
                uptimeField = value;
                RaisePropertyChanged("uptime");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string refresh_rate
        {
            get { return refresh_rateField; }
            set
            {
                refresh_rateField = value;
                RaisePropertyChanged("refresh_rate");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_home
        {
            get { return my_homeField; }
            set
            {
                my_homeField = value;
                RaisePropertyChanged("my_home");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string limit
        {
            get { return limitField; }
            set
            {
                limitField = value;
                RaisePropertyChanged("limit");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string have_quota
        {
            get { return have_quotaField; }
            set
            {
                have_quotaField = value;
                RaisePropertyChanged("have_quota");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isverbose
        {
            get { return isverboseField; }
            set
            {
                isverboseField = value;
                RaisePropertyChanged("isverbose");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string start
        {
            get { return startField; }
            set
            {
                startField = value;
                RaisePropertyChanged("start");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string finish
        {
            get { return finishField; }
            set
            {
                finishField = value;
                RaisePropertyChanged("finish");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version
        {
            get { return versionField; }
            set
            {
                versionField = value;
                RaisePropertyChanged("version");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string new_rel_url
        {
            get { return new_rel_urlField; }
            set
            {
                new_rel_urlField = value;
                RaisePropertyChanged("new_rel_url");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string my_lcldata
        {
            get { return my_lcldataField; }
            set
            {
                my_lcldataField = value;
                RaisePropertyChanged("my_lcldata");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color_scheme
        {
            get { return color_schemeField; }
            set
            {
                color_schemeField = value;
                RaisePropertyChanged("color_scheme");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diskspacetotal1
        {
            get { return diskspacetotal1Field; }
            set
            {
                diskspacetotal1Field = value;
                RaisePropertyChanged("diskspacetotal1");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nt
        {
            get { return ntField; }
            set
            {
                ntField = value;
                RaisePropertyChanged("nt");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status
        {
            get { return statusField; }
            set
            {
                statusField = value;
                RaisePropertyChanged("status");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_warning
        {
            get { return last_warningField; }
            set
            {
                last_warningField = value;
                RaisePropertyChanged("last_warning");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string have_warnings
        {
            get { return have_warningsField; }
            set
            {
                have_warningsField = value;
                RaisePropertyChanged("have_warnings");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cache_art
        {
            get { return cache_artField; }
            set
            {
                cache_artField = value;
                RaisePropertyChanged("cache_art");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sizeleft
        {
            get { return sizeleftField; }
            set
            {
                sizeleftField = value;
                RaisePropertyChanged("sizeleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string finishaction
        {
            get { return finishactionField; }
            set
            {
                finishactionField = value;
                RaisePropertyChanged("finishaction");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paused_all
        {
            get { return paused_allField; }
            set
            {
                paused_allField = value;
                RaisePropertyChanged("paused_all");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quota
        {
            get { return quotaField; }
            set
            {
                quotaField = value;
                RaisePropertyChanged("quota");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newzbin_url
        {
            get { return newzbin_urlField; }
            set
            {
                newzbin_urlField = value;
                RaisePropertyChanged("newzbin_url");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string new_release
        {
            get { return new_releaseField; }
            set
            {
                new_releaseField = value;
                RaisePropertyChanged("new_release");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pause_int
        {
            get { return pause_intField; }
            set
            {
                pause_intField = value;
                RaisePropertyChanged("pause_int");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mbleft
        {
            get { return mbleftField; }
            set
            {
                mbleftField = value;
                RaisePropertyChanged("mbleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diskspace1
        {
            get { return diskspace1Field; }
            set
            {
                diskspace1Field = value;
                RaisePropertyChanged("diskspace1");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scripts
        {
            get { return scriptsField; }
            set
            {
                scriptsField = value;
                RaisePropertyChanged("scripts");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string darwin
        {
            get { return darwinField; }
            set
            {
                darwinField = value;
                RaisePropertyChanged("darwin");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timeleft
        {
            get { return timeleftField; }
            set
            {
                timeleftField = value;
                RaisePropertyChanged("timeleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mb
        {
            get { return mbField; }
            set
            {
                mbField = value;
                RaisePropertyChanged("mb");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string noofslots
        {
            get { return noofslotsField; }
            set
            {
                noofslotsField = value;
                RaisePropertyChanged("noofslots");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eta
        {
            get { return etaField; }
            set
            {
                etaField = value;
                RaisePropertyChanged("eta");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diskspacetotal2
        {
            get { return diskspacetotal2Field; }
            set
            {
                diskspacetotal2Field = value;
                RaisePropertyChanged("diskspacetotal2");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nzb_quota
        {
            get { return nzb_quotaField; }
            set
            {
                nzb_quotaField = value;
                RaisePropertyChanged("nzb_quota");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string loadavg
        {
            get { return loadavgField; }
            set
            {
                loadavgField = value;
                RaisePropertyChanged("loadavg");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cache_max
        {
            get { return cache_maxField; }
            set
            {
                cache_maxField = value;
                RaisePropertyChanged("cache_max");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kbpersec
        {
            get { return kbpersecField; }
            set
            {
                kbpersecField = value;
                RaisePropertyChanged("kbpersec");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string speedlimit
        {
            get { return speedlimitField; }
            set
            {
                speedlimitField = value;
                RaisePropertyChanged("speedlimit");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string webdir
        {
            get { return webdirField; }
            set
            {
                webdirField = value;
                RaisePropertyChanged("webdir");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queue_details
        {
            get { return queue_detailsField; }
            set
            {
                queue_detailsField = value;
                RaisePropertyChanged("queue_details");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string left_quota
        {
            get { return left_quotaField; }
            set
            {
                left_quotaField = value;
                RaisePropertyChanged("left_quota");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diskspace2
        {
            get { return diskspace2Field; }
            set
            {
                diskspace2Field = value;
                RaisePropertyChanged("diskspace2");
            }
        }

       
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("slot", typeof (queueSlotsSlot),
            Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public queueSlotsSlot[] slots
        {
            get { return slotsField; }
            set
            {
                slotsField = value;
                RaisePropertyChanged("slots");
            }
        }

       
        [XmlElementAttribute("categories", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public queueCategories[] categories
        {
            get { return categoriesField; }
            set
            {
                categoriesField = value;
                RaisePropertyChanged("categories");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

   
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class queueSlotsSlot : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string statusField;

        private string indexField;

        private string etaField;

        private string missingField;

        private string avg_ageField;

        private string scriptField;

        private string msgidField;

        private string verbosityField;

        private double mbField;

        private string sizeleftField;

        private string filenameField;

        private string priorityField;

        private string catField;

        private double mbleftField;

        private string timeleftField;

        private string percentageField;

        private string nzo_idField;

        private string unpackoptsField;

        private string sizeField;

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status
        {
            get { return statusField; }
            set
            {
                statusField = value;
                RaisePropertyChanged("status");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string index
        {
            get { return indexField; }
            set
            {
                indexField = value;
                RaisePropertyChanged("index");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eta
        {
            get { return etaField; }
            set
            {
                etaField = value;
                RaisePropertyChanged("eta");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string missing
        {
            get { return missingField; }
            set
            {
                missingField = value;
                RaisePropertyChanged("missing");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avg_age
        {
            get { return avg_ageField; }
            set
            {
                avg_ageField = value;
                RaisePropertyChanged("avg_age");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string script
        {
            get { return scriptField; }
            set
            {
                scriptField = value;
                RaisePropertyChanged("script");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgid
        {
            get { return msgidField; }
            set
            {
                msgidField = value;
                RaisePropertyChanged("msgid");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string verbosity
        {
            get { return verbosityField; }
            set
            {
                verbosityField = value;
                RaisePropertyChanged("verbosity");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double mb
        {
            get { return mbField; }
            set
            {
                mbField = value;
                RaisePropertyChanged("mb");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sizeleft
        {
            get { return sizeleftField; }
            set
            {
                sizeleftField = value;
                RaisePropertyChanged("sizeleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filename
        {
            get { return filenameField; }
            set
            {
                filenameField = value;
                RaisePropertyChanged("filename");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string priority
        {
            get { return priorityField; }
            set
            {
                priorityField = value;
                RaisePropertyChanged("priority");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cat
        {
            get { return catField; }
            set
            {
                catField = value;
                RaisePropertyChanged("cat");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double mbleft
        {
            get { return mbleftField; }
            set
            {
                mbleftField = value;
                RaisePropertyChanged("mbleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timeleft
        {
            get { return timeleftField; }
            set
            {
                timeleftField = value;
                RaisePropertyChanged("timeleft");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string percentage
        {
            get { return percentageField; }
            set
            {
                percentageField = value;
                RaisePropertyChanged("percentage");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nzo_id
        {
            get { return nzo_idField; }
            set
            {
                nzo_idField = value;
                RaisePropertyChanged("nzo_id");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unpackopts
        {
            get { return unpackoptsField; }
            set
            {
                unpackoptsField = value;
                RaisePropertyChanged("unpackopts");
            }
        }

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string size
        {
            get { return sizeField; }
            set
            {
                sizeField = value;
                RaisePropertyChanged("size");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

   
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class queueCategories : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string categoryField;

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string category
        {
            get { return categoryField; }
            set
            {
                categoryField = value;
                RaisePropertyChanged("category");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class result : object, System.ComponentModel.INotifyPropertyChanged
    {
        public static result Deserialize(byte[] data)
        {
            MemoryStream ms = new MemoryStream(data);
            XmlSerializer serializer = new XmlSerializer(typeof(result));
            try
            {
                result r = (result)serializer.Deserialize(ms);
                return r;
            }
            catch
            {
                return null;
            }
        }

        private string statusField;
        private string errorField;

       
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status
        {
            get { return statusField; }
            set
            {
                statusField = value;
                RaisePropertyChanged("status");
            }
        }

        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string error
        {
            get { return errorField; }
            set
            {
                errorField = value;
                RaisePropertyChanged("error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

   
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    public class NewDataSet : object, System.ComponentModel.INotifyPropertyChanged
    {

        private queue[] itemsField;

       
        [XmlElementAttribute("queue")]
        public queue[] Items
        {
            get { return itemsField; }
            set
            {
                itemsField = value;
                RaisePropertyChanged("Items");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
} // namespace
