image: Visual Studio 2026

branches:
  only:
  - master

before_build:
- cmd: nuget restore -verbosity detailed -PackagesDirectory TVRename\packages

before_build:
- cmd: nuget restore -PackagesDirectory TVRename\packages

build:
  project: TVRename.slnx

