//
// Main website for TVRename is http://tvrename.com
//
// Source code available at https://github.com/TV-Rename/tvrename
//
// Copyright (c) TV Rename. This code is released under GPLv3 https://github.com/TV-Rename/tvrename/blob/master/LICENSE.md
//

using Alphaleonis.Win32.Filesystem;
using NodaTime;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Linq;
using TimeZoneConverter;

// These are what is used when processing folders for missing episodes, renaming, etc. of files.

// A "ProcessedEpisode" is generated by processing an Episode from thetvdb, and merging/renaming/etc.
//
// A "ShowItem" is a show the user has added on the "My Shows" tab

namespace TVRename;

public class ShowConfiguration : MediaConfiguration
{
    public string AutoAddFolderBase;
    public string AutoAddCustomFolderFormat;
    public AutomaticFolderType AutoAddType;

    public bool CountSpecials;
    public bool DvdOrder; // sort by DVD order, not the default sort we get
    public bool AlternateOrder;
    public readonly List<int> IgnoreSeasons;
    public readonly ConcurrentDictionary<int, List<string>> ManualFolderLocations;
    public readonly ConcurrentDictionary<int, List<ShowRule>> SeasonRules;
    public bool ShowNextAirdate;
    public bool UseSequentialMatch;
    public bool UseEpNameMatch;
    public bool UseAirDateMatch;
    public bool UseCustomSearchUrl;
    public string CustomSearchUrl;
    public bool UseCustomNamingFormat;
    public string CustomNamingFormat;
    public bool ManualFoldersReplaceAutomatic;

    private readonly EpisodeDenormalisations EpisodeCaches = new ();

    public string ShowTimeZone { get; internal set; }
    private DateTimeZone? seriesTimeZone;
    private string lastFiguredTz;
    public DateTime? BannersLastUpdatedOnDisk { get; set; }
    public ProcessedSeason.SeasonType Order =>
        AlternateOrder ? ProcessedSeason.SeasonType.alternate :
        DvdOrder ? ProcessedSeason.SeasonType.dvd :
        ProcessedSeason.SeasonType.aired;
    private static readonly NLog.Logger Logger = NLog.LogManager.GetCurrentClassLogger();

    #region AutomaticFolderType enum

    public enum AutomaticFolderType
    {
        none,
        baseOnly,
        libraryDefaultFolderFormat,
        customFolderFormat
    }

    #endregion AutomaticFolderType enum

    public ShowConfiguration()
    {
        ManualFolderLocations = new ConcurrentDictionary<int, List<string>>();
        SeasonRules = new ConcurrentDictionary<int, List<ShowRule>>();

        IgnoreSeasons = [];

        UseCustomRegion = false;
        CustomRegionCode = string.Empty;

        UseCustomShowName = false;
        CustomShowName = string.Empty;
        UseCustomLanguage = false;
        TvdbCode = -1;
        TVmazeCode = -1;
        TmdbCode = -1;
        UseCustomSearchUrl = false;
        CustomSearchUrl = string.Empty;
        UseCustomNamingFormat = false;
        CustomNamingFormat = string.Empty;
        ManualFoldersReplaceAutomatic = false;
        BannersLastUpdatedOnDisk = null; //assume that the banners are old and have expired
        ShowTimeZone = TVSettings.Instance.DefaultShowTimezoneName ?? TimeZoneHelper.DefaultTimeZone(); // default, is correct for most shows
        lastFiguredTz = string.Empty;

        UseSequentialMatch = TVSettings.Instance.DefShowSequentialMatching;
        UseAirDateMatch = TVSettings.Instance.DefShowAirDateMatching;
        UseEpNameMatch = TVSettings.Instance.DefShowEpNameMatching;
        ShowNextAirdate = TVSettings.Instance.DefShowNextAirdate;
        DoRename = TVSettings.Instance.DefShowDoRenaming;
        DoMissingCheck = TVSettings.Instance.DefShowDoMissingCheck;
        CountSpecials = TVSettings.Instance.DefShowSpecialsCount;
        DvdOrder = TVSettings.Instance.DefShowDVDOrder;
        AlternateOrder = TVSettings.Instance.DefShowAlternateOrder;
        ForceCheckNoAirdate = TVSettings.Instance.DefShowIncludeNoAirdate;
        ForceCheckFuture = TVSettings.Instance.DefShowIncludeFuture;

        AutoAddCustomFolderFormat = CustomSeasonName.DefaultStyle();

        AutoAddFolderBase =
            !TVSettings.Instance.DefShowAutoFolders ? string.Empty
            : !TVSettings.Instance.DefShowUseDefLocation ? string.Empty
            : TVSettings.Instance.DefShowLocation.ToNonNullString().EnsureEndsWithSeparator() + TVSettings.Instance.DefaultTVShowFolder(this);

        AutoAddType =
            !TVSettings.Instance.DefShowAutoFolders ? AutomaticFolderType.none
            : TVSettings.Instance.DefShowUseBase ? AutomaticFolderType.baseOnly
            : AutomaticFolderType.libraryDefaultFolderFormat;
    }

    public ShowConfiguration(int code, TVDoc.ProviderType type) : this()
    {
        ConfigurationProvider = type;
        SetId(type, code);
    }

    public string ShowStatus => CachedShow?.Status ?? "Unknown";

    public int GetSeasonIndex(int seasonNumber)
    {
        List<int> seasonNumbers = [.. AppropriateSeasons().Values.ToList().Where(season => !season.IsSpecial).Select(sn => sn.SeasonNumber)];

        seasonNumbers.Sort();

        return seasonNumbers.IndexOf(seasonNumber) + 1;
    }

    private bool HasAnyAirdates(int snum)
    {
        return AppropriateSeasons().TryGetValue(snum, out ProcessedSeason? season)
               && season.Episodes.Values.Any(e => e.FirstAired != null);
    }

    //todo use this function MS_SI_CHANGE
    internal void RemoveEpisode(int episodeId)
    {
        //Remove from Aired and DVD Seasons
        EpisodeCaches.dvdSeasons.Values.ForEach(s => s.RemoveEpisode(episodeId));
        EpisodeCaches.airedSeasons.Values.ForEach(s => s.RemoveEpisode(episodeId));
    }

    /// <exception cref="EpisodeNotFoundException">Condition.</exception>
    internal ProcessedEpisode GetEpisode(int seasF, int epF)
    {
        if (EpisodeCaches.SeasonEpisodes.TryGetValue(seasF, out List<ProcessedEpisode>? season))
        {
            foreach (ProcessedEpisode pep in season.Where(pep => pep.AppropriateEpNum == epF))
            {
                return pep;
            }
        }

        throw new EpisodeNotFoundException();
    }

    public DateTime? LastAiredDate
    {
        get
        {
            DateTime? returnValue = null;
            foreach (ProcessedSeason s in EpisodeCaches.airedSeasons.Values) //We can use AiredSeasons as it does not matter which order we do this in Aired or DVD
            {
                DateTime? seasonLastAirDate = s.LastAiredDate();

                if (!seasonLastAirDate.HasValue)
                {
                    continue;
                }

                if (!returnValue.HasValue)
                {
                    returnValue = seasonLastAirDate.Value;
                }
                else if (DateTime.Compare(seasonLastAirDate.Value, returnValue.Value) > 0)
                {
                    returnValue = seasonLastAirDate.Value;
                }
            }
            return returnValue;
        }
    }

    private DateTimeZone FigureOutTimeZone()
    {
        string tzstr = ShowTimeZone;

        if (string.IsNullOrEmpty(tzstr))
        {
            tzstr = TimeZoneHelper.DefaultTimeZone();
        }

        try
        {
            return DateTimeZoneProviders.Tzdb[tzstr];
        }
        catch (Exception ex)
        {
            LOGGER.Info($"Could not work out what timezone '{ShowName}' has. In the settings it uses '{tzstr}', Testing to see whether it needs to be upgraded: {ex.ErrorText()}");
            try
            {
                tzstr = TZConvert.WindowsToIana(tzstr);
                ShowTimeZone = tzstr;
                lastFiguredTz = tzstr;
                return DateTimeZoneProviders.Tzdb[tzstr];
            }
            catch (Exception ex2)
            {
                LOGGER.Warn(ex2,
                    $"Could not work out what timezone '{ShowName}' has. In the settings it uses '{tzstr}', but that is not valid. Please update. Using the default timezone {TimeZoneHelper.DefaultTimeZone()} for the show instead.");

                try
                {
                    tzstr = TimeZoneHelper.DefaultTimeZone();
                    ShowTimeZone = tzstr;
                    lastFiguredTz = tzstr;
                    return DateTimeZoneProviders.Tzdb[tzstr];
                }
                catch (Exception ex3)
                {
                    LOGGER.Warn(ex3,
                        $"Could not work out what timezone '{ShowName}' has. In the settings it uses '{tzstr}', but that is not valid. Tried to use the default timezone {TimeZoneHelper.DefaultTimeZone()} for the show instead - also invalid.  Please update.");

                    ShowTimeZone = DateTimeZoneProviders.Tzdb.GetSystemDefault().Id;
                    lastFiguredTz = tzstr;
                    return DateTimeZoneProviders.Tzdb.GetSystemDefault();
                }
            }
        }
    }

    public DateTimeZone GetTimeZone()
    {
        if (seriesTimeZone is null || lastFiguredTz != ShowTimeZone)
        {
            seriesTimeZone = FigureOutTimeZone();
        }
        return seriesTimeZone;
    }

    public ShowConfiguration(XElement xmlSettings) : this()
    {
        CustomShowName = xmlSettings.ExtractString("ShowName");
        UseCustomShowName = xmlSettings.ExtractBool("UseCustomShowName", false);
        UseCustomLanguage = xmlSettings.ExtractBool("UseCustomLanguage", false);
        UseCustomRegion = xmlSettings.ExtractBool("UseCustomRegion", false);
        CustomRegionCode = xmlSettings.ExtractString("CustomRegionCode");
        CustomLanguageCode = xmlSettings.ExtractString("CustomLanguageCode");
        CustomShowName = xmlSettings.ExtractString("CustomShowName");
        TvdbCode = xmlSettings.ExtractInt("TVDBID", -1);
        TVmazeCode = xmlSettings.ExtractInt("TVMAZEID", -1);
        TmdbCode = xmlSettings.ExtractInt("TMDBID", -1);
        LastName = xmlSettings.ExtractStringOrNull("LastName");
        ImdbCode = xmlSettings.ExtractStringOrNull("ImdbCode");

        CountSpecials = xmlSettings.ExtractBool("CountSpecials", false);
        ShowNextAirdate = xmlSettings.ExtractBool("ShowNextAirdate", true);
        AutoAddFolderBase = xmlSettings.ExtractString("FolderBase");
        DoRename = xmlSettings.ExtractBool("DoRename", true);
        DoMissingCheck = xmlSettings.ExtractBool("DoMissingCheck", true);
        DvdOrder = xmlSettings.ExtractBool("DVDOrder", false);
        AlternateOrder = xmlSettings.ExtractBool("AlternateOrder", false);
        UseCustomSearchUrl = xmlSettings.ExtractBool("UseCustomSearchURL", false);
        CustomSearchUrl = xmlSettings.ExtractString("CustomSearchURL");
        UseCustomNamingFormat = xmlSettings.ExtractBool("UseCustomNamingFormat", false);
        CustomNamingFormat = xmlSettings.ExtractString("CustomNamingFormat");
        ShowTimeZone = xmlSettings.ExtractStringOrNull("TimeZone") ?? TimeZoneHelper.DefaultTimeZone(); // default, is correct for most shows
        ForceCheckFuture = xmlSettings.ExtractBoolBackupDefault("ForceCheckFuture", "ForceCheckAll", false);
        ForceCheckNoAirdate = xmlSettings.ExtractBoolBackupDefault("ForceCheckNoAirdate", "ForceCheckAll", false);
        AutoAddCustomFolderFormat = xmlSettings.ExtractStringOrNull("CustomFolderFormat") ?? CustomSeasonName.DefaultStyle();
        AutoAddType = GetAutoAddType(xmlSettings.ExtractInt("AutoAddType"));
        ConfigurationProvider = GetConfigurationProviderType(xmlSettings.ExtractInt("ConfigurationProvider"));

        BannersLastUpdatedOnDisk = xmlSettings.ExtractDateTime("BannersLastUpdatedOnDisk");
        UseSequentialMatch = xmlSettings.ExtractBool("UseSequentialMatch", false);
        UseAirDateMatch = xmlSettings.ExtractBool("UseAirDateMatch", false);
        UseEpNameMatch = xmlSettings.ExtractBool("UseEpNameMatch", false);
        ManualFoldersReplaceAutomatic = xmlSettings.ExtractBool("ManualFoldersReplaceAutomatic", false);

        SetupIgnoreRules(xmlSettings);
        SetupAliases(xmlSettings);
        SetupSeasonRules(xmlSettings);
        SetupSeasonFolders(xmlSettings);
        UpgradeFromOldSeasonFormat(xmlSettings);
    }

    private static AutomaticFolderType GetAutoAddType(int? value)
    {
        return value is null ? AutomaticFolderType.libraryDefaultFolderFormat : (AutomaticFolderType)value;
    }

    private void UpgradeFromOldSeasonFormat(XElement xmlSettings)
    {
        //These variables have been discontinued (JULY 2018).  If we have any then we should migrate to the new values
        bool upgradeFromOldAutoAddFunction = xmlSettings.Descendants("AutoAddNewSeasons").Any()
                                             || xmlSettings.Descendants("FolderPerSeason").Any()
                                             || xmlSettings.Descendants("SeasonFolderName").Any()
                                             || xmlSettings.Descendants("PadSeasonToTwoDigits").Any();
        bool tempAutoAddNewSeasons = xmlSettings.ExtractBool("AutoAddNewSeasons", true);
        bool tempAutoAddFolderPerSeason = xmlSettings.ExtractBool("FolderPerSeason", true);
        string tempAutoAddSeasonFolderName = xmlSettings.ExtractString("SeasonFolderName");
        bool tempPadSeasonToTwoDigits = xmlSettings.ExtractBool("PadSeasonToTwoDigits", true);

        if (upgradeFromOldAutoAddFunction)
        {
            if (tempAutoAddNewSeasons)
            {
                if (tempAutoAddFolderPerSeason)
                {
                    AutoAddCustomFolderFormat = tempAutoAddSeasonFolderName + (tempPadSeasonToTwoDigits || TVSettings.Instance.LeadingZeroOnSeason ? "{Season:2}" : "{Season}");
                    AutoAddType = AutoAddCustomFolderFormat == TVSettings.Instance.SeasonFolderFormat
                        ? AutomaticFolderType.libraryDefaultFolderFormat
                        : AutomaticFolderType.customFolderFormat;
                }
                else
                {
                    AutoAddCustomFolderFormat = string.Empty;
                    AutoAddType = AutomaticFolderType.baseOnly;
                }
            }
            else
            {
                AutoAddCustomFolderFormat = string.Empty;
                AutoAddType = AutomaticFolderType.none;
            }
        }
    }

    private void SetupIgnoreRules(XElement xmlSettings)
    {
        foreach (int seasonNumber in xmlSettings.Descendants("IgnoreSeasons").Descendants("Ignore").Select(ig => XmlConvert.ToInt32(ig.Value)).Distinct())
        {
            IgnoreSeasons.Add(seasonNumber);
        }
    }

    private void SetupSeasonRules(XElement xmlSettings)
    {
        foreach (XElement rulesSet in xmlSettings.Descendants("Rules"))
        {
            XAttribute? value = rulesSet.Attribute("SeasonNumber");
            if (value is null)
            {
                continue;
            }

            int snum = int.Parse(value.Value);
            SeasonRules[snum] = [];

            foreach (XElement ruleData in rulesSet.Descendants("Rule"))
            {
                SeasonRules[snum].Add(new ShowRule(ruleData));
            }
        }
    }

    private void SetupSeasonFolders(XElement xmlSettings)
    {
        foreach (XElement seasonFolder in xmlSettings.Descendants("SeasonFolders"))
        {
            XAttribute? value = seasonFolder.Attribute("SeasonNumber");
            if (value is null)
            {
                continue;
            }

            int snum = int.Parse(value.Value);

            ManualFolderLocations[snum] =
            [
                .. seasonFolder.Descendants("Folder")
                             .Select(folderData => folderData.Attribute("Location")?.Value)
                             .Distinct()
                             .OfType<string>()
                             .Where(ff => !string.IsNullOrWhiteSpace(ff) && AutoFolderNameForSeason(snum) != ff),
            ];
        }
    }

    internal bool UsesManualFolders() => !ManualFolderLocations.IsEmpty;

    public override ProcessedSeason.SeasonType SeasonOrder => Order;

    protected override MediaType GetMediaType() => MediaType.tv;

    protected override MediaCache LocalCache()
    {
        return LocalCache(Provider == TVDoc.ProviderType.libraryDefault ? TVSettings.Instance.DefaultProvider : Provider);
    }

    private static MediaCache LocalCache(TVDoc.ProviderType provider) => TVDoc.GetMediaCache(provider);

    public enum ShowAirStatus
    {
        noEpisodesOrSeasons,
        aired,
        partiallyAired,
        noneAired
    }

    public ShowAirStatus SeasonsAirStatus
    {
        get
        {
            if (!HasSeasonsAndEpisodes)
            {
                return ShowAirStatus.noEpisodesOrSeasons;
            }

            if (HasAiredEpisodes && !HasUnairedEpisodes)
            {
                return ShowAirStatus.aired;
            }

            if (HasUnairedEpisodes && !HasAiredEpisodes)
            {
                return ShowAirStatus.noneAired;
            }

            if (HasAiredEpisodes && HasUnairedEpisodes)
            {
                return ShowAirStatus.partiallyAired;
            }

            //System.Diagnostics.Debug.Assert(false, "That is weird ... we have 'seasons and episodes' but none are aired, nor unaired. That case shouldn't actually occur !");
            return ShowAirStatus.noEpisodesOrSeasons;
        }
    }

    private bool HasSeasonsAndEpisodes
    {
        get
        {
            //We can use AiredSeasons as it does not matter which order we do this in Aired or DVD
            CachedSeriesInfo? cachedSeriesInfo = CachedData as CachedSeriesInfo;
            if (cachedSeriesInfo?.Episodes is null || cachedSeriesInfo.Episodes.Count <= 0)
            {
                return false;
            }

            return true;
        }
    }

    private bool HasUnairedEpisodes
    {
        get
        {
            if (!HasSeasonsAndEpisodes)
            {
                return false;
            }

            foreach (KeyValuePair<int, ProcessedSeason> s in EpisodeCaches.airedSeasons)
            {
                if (IgnoreSeasons.Contains(s.Key))
                {
                    continue;
                }

                if (TVSettings.Instance.IgnoreAllSpecials && s.Key == 0)
                {
                    continue;
                }

                if (s.Value.Status(GetTimeZone()) == ProcessedSeason.SeasonStatus.noneAired ||
                    s.Value.Status(GetTimeZone()) == ProcessedSeason.SeasonStatus.partiallyAired)
                {
                    return true;
                }
            }

            return false;
        }
    }

    private bool HasAiredEpisodes
    {
        get
        {
            if (!HasSeasonsAndEpisodes)
            {
                return false;
            }

            foreach (KeyValuePair<int, ProcessedSeason> s in EpisodeCaches.airedSeasons)
            {
                if (IgnoreSeasons.Contains(s.Key))
                {
                    continue;
                }

                if (TVSettings.Instance.IgnoreAllSpecials && s.Key == 0)
                {
                    continue;
                }

                if (s.Value.Status(GetTimeZone()) == ProcessedSeason.SeasonStatus.partiallyAired || s.Value.Status(GetTimeZone()) == ProcessedSeason.SeasonStatus.aired)
                {
                    return true;
                }
            }
            return false;
        }
    }

    public IEnumerable<KeyValuePair<int, List<ProcessedEpisode>>> ActiveSeasons
    {
        get
        {
            return EpisodeCaches.SeasonEpisodes
                .Where(pair => !IgnoreSeasons.Contains(pair.Key)) //not an ignored season
                .Where(pair => !(pair.Key == 0 && TVSettings.Instance.IgnoreAllSpecials)) //not a specials where all specials are ignored
                .Where(pair => !(pair.Key == 0 && CountSpecials)); //not a specials where this shows specials are ignored
        }
    }

    public string? WebsiteUrl
    {
        get
        {
            return Provider switch
            {
                TVDoc.ProviderType.TheTVDB => TheTVDB.API.WebsiteShowUrl(this),
                TVDoc.ProviderType.TMDB => TMDB.API.WebsiteShowUrl(this),
                _ => CachedShow?.Slug
            };
        }
    }

    protected override TVDoc.ProviderType DefaultProvider() => TVSettings.Instance.DefaultProvider;

    public List<ShowRule>? RulesForSeason(int n)
    {
        return SeasonRules.TryGetValue(n, out List<ShowRule>? rule) ? rule : null;
    }

    private string AutoFolderNameForSeason(ProcessedSeason? s)
    {
        string r = AutoAddFolderBase;
        if (string.IsNullOrEmpty(r))
        {
            return string.Empty;
        }

        if (s is null)
        {
            return string.Empty;
        }

        if (!r.EndsWith(System.IO.Path.DirectorySeparatorChar.ToString(), StringComparison.Ordinal))
        {
            r += System.IO.Path.DirectorySeparatorChar;
        }

        if (AutoAddType == AutomaticFolderType.none)
        {
            return r;
        }

        if (AutoAddType == AutomaticFolderType.baseOnly)
        {
            return r;
        }

        if (s.IsSpecial)
        {
            return r + TVSettings.Instance.SpecialsFolderName;
        }

        if (AutoAddType == AutomaticFolderType.libraryDefaultFolderFormat)
        {
            return r + CustomSeasonName.NameFor(s, TVSettings.Instance.SeasonFolderFormat);
        }

        if (AutoAddType == AutomaticFolderType.customFolderFormat)
        {
            return r + CustomSeasonName.NameFor(s, AutoAddCustomFolderFormat);
        }

        return r;
    }

    public int MaxSeason()
    {
        int max = 0;
        foreach (KeyValuePair<int, List<ProcessedEpisode>> kvp in EpisodeCaches.SeasonEpisodes)
        {
            if (kvp.Key > max)
            {
                max = kvp.Key;
            }
        }
        return max;
    }

    public void WriteXmlSettings(XmlWriter writer)
    {
        writer.WriteStartElement("ShowItem");

        writer.WriteElement("UseCustomShowName", UseCustomShowName);
        writer.WriteElement("CustomShowName", CustomShowName);
        writer.WriteElement("UseCustomLanguage", UseCustomLanguage);
        writer.WriteElement("CustomLanguageCode", CustomLanguageCode);
        writer.WriteElement("UseCustomRegion", UseCustomRegion);
        writer.WriteElement("CustomRegionCode", CustomRegionCode);
        writer.WriteElement("ShowNextAirdate", ShowNextAirdate);
        writer.WriteElement("TVDBID", TvdbCode);
        writer.WriteElement("TVMAZEID", TVmazeCode);
        writer.WriteElement("TMDBID", TmdbCode);
        writer.WriteElement("LastName", LastName);
        writer.WriteElement("ImdbCode", ImdbCode);
        writer.WriteElement("FolderBase", AutoAddFolderBase);
        writer.WriteElement("DoRename", DoRename);
        writer.WriteElement("DoMissingCheck", DoMissingCheck);
        writer.WriteElement("CountSpecials", CountSpecials);
        writer.WriteElement("DVDOrder", DvdOrder);
        writer.WriteElement("AlternateOrder", AlternateOrder);
        writer.WriteElement("ForceCheckNoAirdate", ForceCheckNoAirdate);
        writer.WriteElement("ForceCheckFuture", ForceCheckFuture);
        writer.WriteElement("UseSequentialMatch", UseSequentialMatch);
        writer.WriteElement("UseAirDateMatch", UseAirDateMatch);
        writer.WriteElement("UseEpNameMatch", UseEpNameMatch);
        writer.WriteElement("CustomFolderFormat", AutoAddCustomFolderFormat);
        writer.WriteElement("AutoAddType", (int)AutoAddType);
        writer.WriteElement("ConfigurationProvider", (int)ConfigurationProvider);
        writer.WriteElement("BannersLastUpdatedOnDisk", BannersLastUpdatedOnDisk);
        writer.WriteElement("TimeZone", ShowTimeZone);
        writer.WriteElement("ManualFoldersReplaceAutomatic", ManualFoldersReplaceAutomatic);

        writer.WriteStartElement("IgnoreSeasons");
        foreach (int i in IgnoreSeasons)
        {
            writer.WriteElement("Ignore", i);
        }
        writer.WriteEndElement();

        writer.WriteStartElement("AliasNames");
        foreach (string str in AliasNames)
        {
            writer.WriteElement("Alias", str);
        }
        writer.WriteEndElement();

        writer.WriteElement("UseCustomSearchURL", UseCustomSearchUrl);
        writer.WriteElement("CustomSearchURL", CustomSearchUrl);

        writer.WriteElement("UseCustomNamingFormat", UseCustomNamingFormat);
        writer.WriteElement("CustomNamingFormat", CustomNamingFormat);

        foreach (KeyValuePair<int, List<ShowRule>> kvp in SeasonRules)
        {
            if (kvp.Value.Any())
            {
                writer.WriteStartElement("Rules");
                writer.WriteAttributeToXml("SeasonNumber", kvp.Key);

                foreach (ShowRule r in kvp.Value)
                {
                    r.WriteXml(writer);
                }

                writer.WriteEndElement(); // Rules
            }
        }
        foreach (KeyValuePair<int, List<string>> kvp in ManualFolderLocations)
        {
            if (kvp.Value.Any())
            {
                writer.WriteStartElement("SeasonFolders");

                writer.WriteAttributeToXml("SeasonNumber", kvp.Key);

                foreach (string s in kvp.Value)
                {
                    writer.WriteStartElement("Folder");
                    writer.WriteAttributeToXml("Location", s);
                    writer.WriteEndElement(); // Folder
                }

                writer.WriteEndElement(); // Rules
            }
        }
        writer.WriteEndElement(); // ShowItem
    }

    protected override Dictionary<int, SafeList<string>> AllFolderLocations(bool manualToo, bool checkExist)
    {
        Dictionary<int, SafeList<string>> fld = [];

        if (manualToo)
        {
            foreach (KeyValuePair<int, List<string>> kvp in ManualFolderLocations.ToList())
            {
                if (!fld.ContainsKey(kvp.Key))
                {
                    fld[kvp.Key] = [];
                }

                foreach (string s in kvp.Value)
                {
                    fld[kvp.Key].Add(s.TrimSlash());
                }
            }
        }

        if (AutoAddNewSeasons() && !string.IsNullOrEmpty(AutoAddFolderBase))
        {
            foreach (int i in ActiveSeasons.Keys())
            {
                if (ManualFoldersReplaceAutomatic && fld.ContainsKey(i))
                {
                    continue;
                }

                string newName = AutoFolderNameForSeason(i);
                if (string.IsNullOrEmpty(newName))
                {
                    continue;
                }

                if (checkExist && !Directory.Exists(newName)) //todo - make async
                {
                    continue;
                }

                //Now we can add the automated one
                if (!fld.ContainsKey(i))
                {
                    fld[i] = [];
                }

                if (!fld[i].Contains(newName))
                {
                    fld[i].Add(newName.TrimSlash());
                }
            }
        }
        return fld;
    }


    protected async Task<Dictionary<int, SafeList<string>>> AllFolderLocationsAsync(bool manualToo, bool checkExist)
    {
        Dictionary<int, SafeList<string>> fld = [];

        if (manualToo)
        {
            foreach (KeyValuePair<int, List<string>> kvp in ManualFolderLocations.ToList())
            {
                if (!fld.ContainsKey(kvp.Key))
                {
                    fld[kvp.Key] = [];
                }

                foreach (string s in kvp.Value)
                {
                    fld[kvp.Key].Add(s.TrimSlash());
                }
            }
        }

        if (AutoAddNewSeasons() && !string.IsNullOrEmpty(AutoAddFolderBase))
        {
            foreach (int i in ActiveSeasons.Keys())
            {
                if (ManualFoldersReplaceAutomatic && fld.ContainsKey(i))
                {
                    continue;
                }

                string newName = AutoFolderNameForSeason(i);
                if (string.IsNullOrEmpty(newName))
                {
                    continue;
                }

                if (checkExist && !await FileHelper.DirectoryExistsAsync(newName)) { 
                    continue;
                }

                //Now we can add the automated one
                if (!fld.ContainsKey(i))
                {
                    fld[i] = [];
                }

                if (!fld[i].Contains(newName))
                {
                    fld[i].Add(newName.TrimSlash());
                }
            }
        }
        return fld;
    }


    public ProcessedSeason? GetSeason(int snum)
    {
        return AppropriateSeasons().TryGetValue(snum, out ProcessedSeason? season) ? season : null;
    }

    public void AddSeasonRule(int snum, ShowRule sr)
    {
        if (!SeasonRules.TryGetValue(snum, out List<ShowRule>? value))
        {
            value = [];
            SeasonRules[snum] = value;
        }

        value.Add(sr);
    }

    public ConcurrentDictionary<int, ProcessedSeason> AppropriateSeasons() => DvdOrder ? EpisodeCaches.dvdSeasons : EpisodeCaches.airedSeasons;

    public ProcessedSeason? GetFirstAvailableSeason()
    {
        return AppropriateSeasons().Select(x => x.Value).FirstOrDefault();
    }

    public ProcessedEpisode? GetFirstAvailableEpisode()
    {
        return EpisodeCaches.SeasonEpisodes.Values.SelectMany(season => season).FirstOrDefault();
    }

    public bool InOneFolder() => AutoAddType == AutomaticFolderType.baseOnly;

    public string AutoFolderNameForSeason(int snum) => AutoFolderNameForSeason(GetSeason(snum));

    public bool AutoAddNewSeasons() => AutoAddType != AutomaticFolderType.none;

    public bool NoAirdatesUntilNow(int maxSeasonNumber)
    {
        int lastPossibleSeason = EpisodeCaches.SeasonEpisodes.Keys.DefaultIfEmpty(1).Max();

        // for specials "season", see if any season has any aired dates
        // otherwise, check only up to the season we are considering
        int maxSeasonToUse = maxSeasonNumber <= 0 ? lastPossibleSeason : maxSeasonNumber;
        if (maxSeasonToUse < 1)
        {
            try
            {
                LOGGER.Warn(
                    $"{Name} has a problem with series in {Order.PrettyPrint()} order - max={maxSeasonToUse}, keys = {EpisodeCaches.SeasonEpisodes.Keys.ToCsv()}, numberOfEps = {EpisodeCaches.SeasonEpisodes.Count}");
            }
            catch (OverflowException ex)
            {
                LOGGER.Error(
                    $"{Name} has a problem with series in {Order.PrettyPrint()} order - max={maxSeasonToUse}, keys = {EpisodeCaches.SeasonEpisodes.Keys.ToCsv()}, numberOfEps = OVERFLOW",ex);
            }

            return true;
        }

        foreach (int snum in Enumerable.Range(1, maxSeasonToUse))
        {
            if (HasAnyAirdates(snum))
            {
                return false;
            }

            //If the show is in its first season and no episodes have air dates
            if (lastPossibleSeason == 1)
            {
                return false;
            }
        }

        return true;
    }

    public IEnumerable<int> GetSeasonKeys()
    {
        int[] numbers = new int[EpisodeCaches.SeasonEpisodes.Keys.Count];
        EpisodeCaches.SeasonEpisodes.Keys.CopyTo(numbers, 0);
        return numbers;
    }

    public IEnumerable<Episode> EpisodesToUse()
    {
        List<Episode> returnValue = [];
        ConcurrentDictionary<int, ProcessedSeason> seasonsToUse = AppropriateSeasons();

        foreach (KeyValuePair<int, ProcessedSeason> kvp in seasonsToUse)
        {
            if (IgnoreSeasons.Contains(kvp.Value.SeasonNumber))
            {
                continue;
            }

            if (kvp.Value.SeasonNumber == 0 && TVSettings.Instance.IgnoreAllSpecials)
            {
                continue;
            }

            returnValue.AddRange(kvp.Value.Episodes.Values);
        }

        return returnValue;
    }

    internal void UpdateSeasonRules(int mSeasonNumber, List<ShowRule> workingRuleSet)
    {
        SeasonRules[mSeasonNumber] = workingRuleSet;
    }
    
    internal void UpdateEpisodeCaches()
    {
        {
            CachedSeriesInfo? ser = TVDoc.GetMediaCache(Provider).GetSeries(Code);

            if (ser is null)
            {
                Logger.Warn($"Asked to generate episodes for {ShowName}, but this has not yet been downloaded from {Provider.PrettyPrint()}");
                return;
            }
            if (ser != CachedShow)
            {
                Logger.Warn($"Asked to generate episodes for {ShowName}, but current prvider {Provider.PrettyPrint()} has returned different data {ser.Id()} vs {CachedShow?.Id()}");
                return;
            }

            EpisodeCaches.UpdateEpisodeDictionary(ser,this);

            foreach (int snum in AppropriateSeasons().Keys.ToList())
            {
                List<ProcessedEpisode>? pel = GenerateEpisodes(snum, true);
                EpisodeCaches.SeasonEpisodes[snum] = pel ?? [];
            }

            {
                // now, go through and number them all sequentially
                List<int> theKeys = [.. AppropriateSeasons().Keys];
                theKeys.Sort();

                int overallCount = 1;
                foreach (int snum in theKeys)
                {
                    if (snum == 0)
                    {
                        continue;
                    }

                    foreach (ProcessedEpisode pe in EpisodeCaches.SeasonEpisodes[snum])
                    {
                        pe.OverallNumber = overallCount;
                        overallCount += 1 + pe.EpNum2 - pe.AppropriateEpNum;
                    }
                }
            }
        }

    }

    public List<ProcessedEpisode>? GetRawEpisodes(int snum) => GenerateEpisodes(snum, false);
    public List<ProcessedEpisode>? GenerateEpisodes(int snum) => GenerateEpisodes(snum, true);

    /// <exception cref="ArgumentOutOfRangeException">Condition.</exception>
    private List<ProcessedEpisode>? GenerateEpisodes(int snum, bool applyRules)
    {
        if (!AppropriateSeasons().TryGetValue(snum, out ProcessedSeason? seas))
        {
            Logger.Error($"Asked to update season {snum} of {ShowName}, but it does not exist");
            return null;
        }

        List<ProcessedEpisode> eis = [.. seas.Episodes.Values.Select(e => new ProcessedEpisode(e, this))];

        switch (Order)
        {
            case ProcessedSeason.SeasonType.dvd:
                eis.Sort(ProcessedEpisode.DVDOrderSorter);
                AutoMerge(eis);
                Renumber(eis);
                break;

            case ProcessedSeason.SeasonType.aired:
                eis.Sort(ProcessedEpisode.EpNumberSorter);
                break;

            case ProcessedSeason.SeasonType.alternate:
                eis.Sort(ProcessedEpisode.EpNumberSorter);
                break;

            default:
                throw new ArgumentOutOfRangeException("Order", $"GenerateEpisodes: si has invalid Order {Order}");
        }

        if (CountSpecials && AppropriateSeasons().ContainsKey(0) && !TVSettings.Instance.IgnoreAllSpecials)
        {
            // merge specials in
            MergeSpecialsIn(this, snum, eis);
        }

        if (applyRules)
        {
            List<ShowRule>? rules = RulesForSeason(snum);
            if (rules != null)
            {
                ApplyRules(eis, rules);
            }
        }

        return eis;
    }

    private void AutoMerge(List<ProcessedEpisode> eis)
    {
        for (int i = 1; i < eis.Count; i++)
        {
            if (eis[i - 1].DvdEpNum == eis[i].DvdEpNum && eis[i].DvdEpNum > 0)
            {
                //We have a candidate to merge
                MergeEpisodes(eis, RuleAction.kMerge, i - 1, i, null);
            }
        }
    }

    private static void MergeSpecialsIn(ShowConfiguration si, int snum, List<ProcessedEpisode> eis)
    {
        foreach (Episode ep in si.AppropriateSeasons()[0].Episodes.Values)
        {
            MergeEpisode(si, snum, ep, eis);
        }

        // renumber to allow for specials
        int epnumr = 1;
        foreach (ProcessedEpisode t in eis)
        {
            t.SetEpisodeNumbers(epnumr, epnumr + t.EpNum2 - t.AppropriateEpNum);
            epnumr++;
        }
    }

    private static void MergeEpisode(ShowConfiguration si, int snum, Episode ep, List<ProcessedEpisode> eis)
    {
        if (!ep.AirsBeforeSeason.HasValue)
        {
            return;
        }

        if (!ep.AirsBeforeEpisode.HasValue)
        {
            return;
        }

        int sease = ep.AirsBeforeSeason.Value;
        if (sease != snum)
        {
            return;
        }

        int epnum = ep.AirsBeforeEpisode.Value;
        for (int i = 0; i < eis.Count; i++)
        {
            if (eis[i].AppropriateSeasonNumber == sease && eis[i].AppropriateEpNum == epnum)
            {
                ProcessedEpisode pe = new(ep, si)
                {
                    TheAiredProcessedSeason = eis[i].TheAiredProcessedSeason,
                    TheDvdProcessedSeason = eis[i].TheDvdProcessedSeason,
                    SeasonId = eis[i].SeasonId
                };

                eis.Insert(i, pe);
                break;
            }
        }
    }

    public  void ApplyRules(List<ProcessedEpisode> eis, IEnumerable<ShowRule> rules)
    {
        foreach (ShowRule sr in rules)
        {
            ApplyRule(eis, sr);
        } // for each rule

        RemoveIgnoredEpisodes(eis);
    }

    private void ApplyRule(List<ProcessedEpisode> episodes, ShowRule sr)
    {
        try
        {
            // turn nn1 and nn2 from ep number into position in array
            int n1 = FindIndex(episodes, sr.First);
            int n2 = FindIndex(episodes, sr.Second);

            switch (sr.DoWhatNow)
            {
                case RuleAction.kRename:
                    RenameEpisode(episodes, n1, sr.UserSuppliedText);
                    break;

                case RuleAction.kRemove:
                    RemoveEpisode(episodes, n1, n2);
                    break;

                case RuleAction.kIgnoreEp:
                    IgnoreEpisodes(episodes, n1, n2);
                    break;

                case RuleAction.kSplit:
                    SplitEpisode(episodes, sr.Second, n1);
                    break;

                case RuleAction.kMerge:
                case RuleAction.kCollapse:
                    MergeEpisodes(episodes,  sr.DoWhatNow, n1, n2, sr.UserSuppliedText);
                    break;

                case RuleAction.kSwap:
                    SwapEpisode(episodes, n1, n2);
                    break;

                case RuleAction.kInsert:
                    InsertEpisode(episodes,  n1, sr.UserSuppliedText, sr);
                    break;
            }

            if (sr.RenumberAfter)
            {
                Renumber(episodes);
            }
        }
        catch (Exception e)
        {
            Logger.Warn(
                $"Please review rules for {ShowName} season {episodes.FirstOrDefault()?.AppropriateSeasonNumber}");

            Logger.Warn(e,
                $"Could not process rule for {ShowName}, {sr.DoWhatNow}:{sr.First}:{sr.Second}:{sr.UserSuppliedText}");
        }
    }

    private static void RemoveIgnoredEpisodes(List<ProcessedEpisode> eis)
    {
        // now, go through and remove the ignored ones (but don't renumber!!)
        for (int i = eis.Count - 1; i >= 0; i--)
        {
            if (eis[i].Ignore)
            {
                eis.RemoveAt(i);
            }
        }
    }

    private static int FindIndex(List<ProcessedEpisode> eis, int episodeNumber)
    {
        for (int i = 0; i < eis.Count; i++)
        {
            if (eis[i].AppropriateEpNum == episodeNumber)
            {
                return i;
            }
        }
        return -1;
    }

    private static void IgnoreEpisodes(List<ProcessedEpisode> eis, int fromIndex, int toIndex)
    {
        int ec = eis.Count;

        if (toIndex == -1)
        {
            if (ValidIndex(toIndex, ec))
            {
                eis[toIndex].Ignore = true;
            }
        }
        else
        {
            for (int i = fromIndex; i <= toIndex; i++)
            {
                if (ValidIndex(i, ec))
                {
                    eis[i].Ignore = true;
                }
            }
        }
    }

    private static void RemoveEpisode(List<ProcessedEpisode> eis, int fromIndex, int toIndex)
    {
        int ec = eis.Count;
        if (ValidIndex(fromIndex, ec) && ValidIndex(toIndex, ec))
        {
            eis.RemoveRange(fromIndex, 1 + toIndex - fromIndex);
        }
        else if (ValidIndex(fromIndex, ec) && toIndex == -1)
        {
            eis.RemoveAt(fromIndex);
        }
        // ReSharper disable once RedundantIfElseBlock
        else
        {
            //arguments are not consistent, so we'll do nothing
        }
        Renumber(eis);
    }

    private static bool ValidIndex(int index, int maxIndex) => index < maxIndex && index >= 0;

    private static void RenameEpisode(List<ProcessedEpisode> eis, int index, string txt)
    {
        int ec = eis.Count;
        if (ValidIndex(index, ec))
        {
            eis[index].Name = txt;
        }
    }

    private void SplitEpisode(List<ProcessedEpisode> eis, int numberOfNewParts, int index)
    {
        int ec = eis.Count;
        // split one episode into a multi-parter
        if (ValidIndex(index, ec))
        {
            ProcessedEpisode ei = eis[index];
            string nameBase = ei.Name;
            eis.RemoveAt(index); // remove old one

            foreach (int i in Enumerable.Range(1, numberOfNewParts))
            // make numberOfNewParts new parts
            {
                ProcessedEpisode pe2 =
                    new(ei, this, ProcessedEpisode.ProcessedEpisodeType.split)
                    {
                        Name = $"{nameBase} (Part {i})",
                        AiredEpNum = -2,
                        DvdEpNum = -2,
                        EpNum2 = -2
                    };

                eis.Insert(index + i - 1, pe2);
            }
        }
    }

    private void MergeEpisodes(List<ProcessedEpisode> eis,  RuleAction action, int fromIndex, int toIndex, string? newName)
    {
        int ec = eis.Count;
        if (ValidIndex(fromIndex, ec) && ValidIndex(toIndex, ec) && fromIndex < toIndex)
        {
            ProcessedEpisode oldFirstEi = eis[fromIndex];
            List<string> episodeNames = [eis[fromIndex].Name];
            string defaultCombinedName = eis[fromIndex].Name + " + ";
            string combinedSummary = eis[fromIndex].Overview + "<br/><br/>";
            List<Episode> alleps = [eis[fromIndex]];
            for (int i = fromIndex + 1; i <= toIndex; i++)
            {
                episodeNames.Add(eis[i].Name);
                defaultCombinedName += eis[i].Name;
                combinedSummary += eis[i].Overview;
                alleps.Add(eis[i]);
                if (i != toIndex)
                {
                    defaultCombinedName += " + ";
                    combinedSummary += "<br/><br/>";
                }
            }

            eis.RemoveRange(fromIndex, toIndex - fromIndex);

            eis.RemoveAt(fromIndex);

            string combinedName = GetBestNameFor(episodeNames, defaultCombinedName);

            ProcessedEpisode pe2 = new(oldFirstEi, this, alleps)
            {
                Name = string.IsNullOrEmpty(newName) ? combinedName : newName,
                AiredEpNum = oldFirstEi.AiredEpNum,
                DvdEpNum = oldFirstEi.DvdEpNum,
                EpNum2 = action == RuleAction.kMerge ? alleps.Max(episode => episode.GetEpisodeNumber(Order)) : oldFirstEi.AppropriateEpNum,
                Overview = combinedSummary
            };

            eis.Insert(fromIndex, pe2);
        }
    }

    private void InsertEpisode(List<ProcessedEpisode> eis, int index, string txt, ShowRule sr)
    {
        // this only applies for inserting an episode, at the end of the list
        if (sr.First == eis[^1].AppropriateEpNum + 1) // after the last episode
        {
            index = eis.Count;
        }

        int ec = eis.Count;

        if (ValidIndex(index, ec))
        {
            ProcessedEpisode t = eis[index];
            ProcessedEpisode n = new(t, this, txt, t.AiredEpNum + 1, t.DvdEpNum + 1, t.EpNum2 + 1);
            eis.Insert(index, n);
        }
        else if (index == ec)
        {
            ProcessedEpisode t = eis[index - 1];
            ProcessedEpisode n = new(t, this, txt, t.AiredEpNum + 1, t.DvdEpNum + 1, t.EpNum2 + 1);
            eis.Add(n);
        }
        // ReSharper disable once RedundantIfElseBlock
        else
        {
            //Parameters are invalid, so we'll do nothing
        }
    }

    private static void SwapEpisode(List<ProcessedEpisode> eis, int n1, int n2)
    {
        int ec = eis.Count;
        if (ValidIndex(n1, ec) && ValidIndex(n2, ec))
        {
            (eis[n2], eis[n1]) = (eis[n1], eis[n2]);
        }
    }

    public static string GetBestNameFor(List<string> episodeNames, string defaultName)
    {
        string root = StringExtensions.GetCommonStartString(episodeNames);
        int shortestEpisodeName = episodeNames.Min(x => x.Length);
        int longestEpisodeName = episodeNames.Max(x => x.Length);
        bool namesSameLength = shortestEpisodeName == longestEpisodeName;
        bool rootIsIgnored = root.Trim().StartsWith("Episode", StringComparison.OrdinalIgnoreCase) ||
                             root.Trim().StartsWith("Part", StringComparison.OrdinalIgnoreCase);

        if (!namesSameLength || rootIsIgnored || root.Length <= 3 || root.Length <= shortestEpisodeName / 2)
        {
            return defaultName;
        }

        char[] charsToTrim = [',', '.', ';', ':', '-', '('];
        string[] wordsToTrim = ["part", "episode", "pt", "chapter"];

        return root.Trim().TrimEnd(wordsToTrim).Trim().TrimEnd(charsToTrim).Trim();
    }

    private static void Renumber(List<ProcessedEpisode> eis)
    {
        if (eis.Count == 0)
        {
            return; // nothing to do
        }

        // renumber
        // pay attention to specials etc.
        int n = eis[0].AppropriateEpNum == 0 ? 0 : 1;

        foreach (ProcessedEpisode t in eis)
        {
            if (t.AppropriateEpNum == -1)
            {
                continue;
            }

            int num = t.EpNum2 - t.AppropriateEpNum;
            if ((t.AppropriateEpNum != n || t.EpNum2 != n + num) && !(t.Show.Order == ProcessedSeason.SeasonType.dvd && t.NotOnDvd()))
            {
                t.SetEpisodeNumbers(n, n + num);
            }
            n += num + 1;
        }
    }

    internal List<ProcessedEpisode> EpisodesForSeason(int snum) => EpisodeCaches.SeasonEpisodes[snum];

    internal int EpisodeCount() => EpisodeCaches.SeasonEpisodes.Values.Sum(episodes => episodes.Count);

    internal int SeasonCount() => EpisodeCaches.SeasonEpisodes.Count;

    internal ProcessedSeason GetOrAddSeason(int airedSeasonNumber, int seasonId, ProcessedSeason.SeasonType type) => EpisodeCaches.GetOrAddSeason(airedSeasonNumber, seasonId, type, this);

    internal List<ProcessedEpisode>? GetRandomSeasonEpisodes() => EpisodeCaches.SeasonEpisodes.Values.FirstOrDefault(v => v.Count > 0);

    internal List<List<ProcessedEpisode>> GetSortedSeasons() => EpisodeCaches.SeasonEpisodes.OrderBy(v => v.Key).Select(v => v.Value).ToList();

    internal async Task<Dictionary<int, SafeList<string>>> AllFolderLocationsEpCheckAsync(bool checkDirectoryExist)
    {
        return await AllFolderLocationsAsync(true, checkDirectoryExist);
    }

    public CachedSeriesInfo? CachedShow => CachedData as CachedSeriesInfo;

    internal class EpisodeDenormalisations
    {
        internal readonly ConcurrentDictionary<int, List<ProcessedEpisode>> SeasonEpisodes = new(); // built up by applying rules.
        internal readonly ConcurrentDictionary<int, ProcessedSeason> airedSeasons = new();
        internal readonly ConcurrentDictionary<int, ProcessedSeason> dvdSeasons = new();


        internal void UpdateEpisodeDictionary(CachedSeriesInfo ser, ShowConfiguration showConfig)
        {
            { //TODO Do we need to reload SeasonEpisodes too?


                // Regenerate the seasons and episodes from the downloaded episodes info,
                // applying any rules as necessary.This will populate the SeasonEpisodes, airedSeasons, and dvdSeasons dictionaries with the appropriate data.
                ConcurrentDictionary<int, ProcessedSeason> NewAiredSeasons = new();
                ConcurrentDictionary<int, ProcessedSeason> NewDvdSeasons = new();

                foreach (Episode e in ser.Episodes)
                {
                    ProcessedSeason airedProcessedSeason = GetOrAddSeason(e.AiredSeasonNumber, e.SeasonId, showConfig, NewAiredSeasons, ProcessedSeason.SeasonType.aired);
                    airedProcessedSeason.AddUpdateEpisode(e);

                    ProcessedSeason dvdProcessedSeason = GetOrAddSeason(e.DvdSeasonNumber, e.SeasonId, showConfig, NewDvdSeasons, ProcessedSeason.SeasonType.dvd);
                    dvdProcessedSeason.AddUpdateEpisode(e);
                }

                //We have a new version of the seasons and episodes, so we can replace the old ones with the new ones

                foreach (KeyValuePair<int, ProcessedSeason> kvp in NewAiredSeasons)
                {
                    airedSeasons[kvp.Key] = kvp.Value;
                }
                foreach (var kvp in airedSeasons)
                {
                    if (!NewAiredSeasons.ContainsKey(kvp.Key))
                    {
                        airedSeasons.TryRemove(kvp.Key, out _);
                    }
                }
                
                foreach (KeyValuePair<int, ProcessedSeason> kvp in NewDvdSeasons)
                {
                    dvdSeasons[kvp.Key] = kvp.Value;
                }
                foreach (var kvp in dvdSeasons)
                {
                    if (!NewDvdSeasons.ContainsKey(kvp.Key))
                    {
                        dvdSeasons.TryRemove(kvp.Key, out _);
                    }
                }
            }
        }
        
        private static ProcessedSeason GetOrAddSeason(int num, int seasonId, ShowConfiguration showConfig, ConcurrentDictionary<int, ProcessedSeason> dict, ProcessedSeason.SeasonType type)
        {
            if (dict.TryGetValue(num, out ProcessedSeason? season))
            {
                return season;
            }

            ProcessedSeason s = new(showConfig, num, seasonId, type);
            dict[num] = s;

            return s;
        }

        internal ProcessedSeason GetOrAddSeason(int seasonNumber, int seasonId, ProcessedSeason.SeasonType type, ShowConfiguration showConfig)
        {
            return type switch
            {
                ProcessedSeason.SeasonType.aired => GetOrAddSeason(seasonNumber, seasonId, showConfig, airedSeasons, ProcessedSeason.SeasonType.aired),
                ProcessedSeason.SeasonType.dvd => GetOrAddSeason(seasonNumber, seasonId, showConfig, dvdSeasons, ProcessedSeason.SeasonType.dvd),
                _ => throw new ArgumentOutOfRangeException(nameof(type), $"Invalid season type {type}")
            };
        }
    }
}

[Serializable]
public class EpisodeNotFoundException : Exception
{
}
