<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Configures it as a Windows Desktop executable application -->
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>

    <!-- Assembly Metadata -->
    <AssemblyName>TVRename</AssemblyName>
    <RootNamespace>TVRename</RootNamespace>
    <ApplicationIcon>App\app.ico</ApplicationIcon>

    <NoWarn>CA1416</NoWarn>
    
    <!-- Compiler Settings -->
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>

    <!-- Disable auto-generation of AssemblyInfo if you want to keep your Properties\AssemblyInfo.cs -->
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <StartupObject>TVRename.App.Program</StartupObject>
  </PropertyGroup>

  <!-- NuGet Package References -->
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.2.1" />
    <PackageReference Include="AlphaFS" Version="2.2.6" />
    <PackageReference Include="CefSharp.Common.NETCore" Version="152.0.60" />
    <PackageReference Include="CefSharp.WinForms.NETCore" Version="152.0.60" />
    <PackageReference Include="CloudFlareUtilities" Version="1.3.0" />
    <PackageReference Include="GuerrillaNtp" Version="3.1.0" />
    <PackageReference Include="Humanizer" Version="3.0.10" />
    <PackageReference Include="Ical.Net" Version="5.2.3" />
    <PackageReference Include="IMDbApiLib" Version="3.0.0" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageReference Include="MediaInfo.Wrapper.Core" Version="26.1.0" />
    <PackageReference Include="Microsoft.NETCore.Platforms" Version="7.0.4" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="10.0.12" />
    <PackageReference Include="MscVersion" Version="1.0.0.9" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="NLog.OutputDebugString" Version="6.2.1" />
    <PackageReference Include="NLog.Targets.Syslog" Version="7.0.0" />
    <PackageReference Include="NLog.Windows.Forms" Version="6.1.4" />
    <PackageReference Include="NodaTime" Version="3.3.4" />
    <PackageReference Include="ObjectListView.Repack.NET6Plus" Version="2.9.5" />
    <PackageReference Include="Polly" Version="8.8.0" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="SourceGrid" Version="4.4.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="TimeZoneConverter" Version="7.2.0" />
    <PackageReference Include="TMDbLib" Version="3.0.0" />
    <PackageReference Include="WinCopies.WindowsAPICodePack.Shell" Version="2.12.0.2" />
    <PackageReference Update="chromiumembeddedframework.runtime.win-arm64" Version="152.0.6" />
    <PackageReference Update="chromiumembeddedframework.runtime.win-x64" Version="152.0.6" />
    <PackageReference Update="chromiumembeddedframework.runtime.win-x86" Version="152.0.6" />
  </ItemGroup>

</Project>