name: Build & Deploy TV Rename

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: windows-latest  

    env:
      Solution_Name: TVRename.slnx

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Get Version
      id: get_version
      uses: maltoze/get-version-action@v1.0.1

    # Install the .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    - name: Cache NuGet Packages
      uses: actions/cache@v6
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: dotnet publish D:\a\tvrename\tvrename\TVRename.slnx  -t:rebuild -verbosity:minimal --configuration Release -p:Version="${{ steps.get_version.outputs.version-without-v }}" -p:AssemblyVersion="${{ steps.get_version.outputs.version-without-v }}"        -p:FileVersion="${{ steps.get_version.outputs.version-without-v }}" 
    
    - name: List all files
      run: Get-ChildItem -Path D:\a\ -Recurse

    - name: List all nuget files
      run: Get-ChildItem -Path ~/.nuget/packages -Recurse    
    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.3.0
      with:
        # The version of NSIS to install
        nsis-version: 3.12
        
    # Compile the NSIS Installer using the 'makensis' CLI tool
    - name: Compile NSIS Script
      run: |
        makensis /V3 /WX /DVERSION=${{ steps.get_version.outputs.version-without-v }} /DTAG=${{ steps.get_version.outputs.version }} Installer.nsi

    - name: List all files
      run: Get-ChildItem -Path D:\a\ -Recurse

    # 5. Upload the generated .exe installer as a downloadable workflow artifact
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: TVRename-${{ steps.get_version.outputs.version }}-Installer.exe
        path: TVRename-${{ steps.get_version.outputs.version }}-Installer.exe        
        archive: false
        overwrite: true

    - name: Attach Files to Release
      uses: stacksjs/action-releaser@v1.2.11
      with:
        files: |
          TVRename-*-Installer.exe

