name: Build & Deploy TV Rename

on:
  release:
  workflow_dispatch:

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: TVRename.slnx

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Get Version
      id: get_version
      uses: maltoze/get-version-action@v1.0.1

    - name: Patch AssemblyInfo
      uses: secondbounce/assemblyinfo-update@v2
      with:
        # Pass your target version (e.g., from an environment variable or tag)
        version: ${{ steps.get_version.outputs.version-without-v }}
        # Optional: Defaults to true. Recursively updates all matching files.
        recursive: true 

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: 10.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v3

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app package
      run: msbuild D:\a\tvrename\tvrename\TVRename\TVRename.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}
    
    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.3.0
      with:
        # The version of NSIS to install
        nsis-version: v3.12
        
    # Compile the NSIS Installer using the 'makensis' CLI tool
    - name: Compile NSIS Script
      run: |
        makensis /V3 /WX /DVERSION=${{ steps.get_version.outputs.version-without-v }} /DTAG=${{ steps.get_version.outputs.version-without-v }} Installer.nsi

    # 5. Upload the generated .exe installer as a downloadable workflow artifact
    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Windows-Installer
        path: path/to/your/generated_output_installer.exe        
